language: go

go:
  - 1.4
  - 1.5

env:
  - GO15VENDOREXPERIMENT=1

install:
  - mkdir -p "$GOPATH/src/willnorris.com/go"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/willnorris.com/go/gum"
  - go get -v -t -d willnorris.com/go/gum/...

script:
  - go test -v $(go list willnorris.com/go/gum/... | grep -v vendor)
